version: '3'

services:
  discordbot:
    image: discordbot
    container_name: discordbot
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./db:/app/db
    build:
      context: .
      dockerfile: ./Dockerfile